<?php
/**
 * EmailReputationResponse
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  onesignal\client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace onesignal\client\model;

use \ArrayAccess;
use \onesignal\client\ObjectSerializer;

/**
 * EmailReputationResponse Class Doc Comment
 *
 * @category Class
 * @description App-wide email bounce and spam complaint rates, broken out by time window. &#x60;last_24_hours&#x60;, &#x60;last_7_days&#x60;, and &#x60;last_30_days&#x60; each hold the bounce and complaint rates for email delivered in that window.
 * @package  onesignal\client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class EmailReputationResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EmailReputationResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'last_24_hours' => '\onesignal\client\model\EmailReputationWindow',
        'last_7_days' => '\onesignal\client\model\EmailReputationWindow',
        'last_30_days' => '\onesignal\client\model\EmailReputationWindow'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'last_24_hours' => null,
        'last_7_days' => null,
        'last_30_days' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'last_24_hours' => 'last_24_hours',
        'last_7_days' => 'last_7_days',
        'last_30_days' => 'last_30_days'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'last_24_hours' => 'setLast24Hours',
        'last_7_days' => 'setLast7Days',
        'last_30_days' => 'setLast30Days'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'last_24_hours' => 'getLast24Hours',
        'last_7_days' => 'getLast7Days',
        'last_30_days' => 'getLast30Days'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['last_24_hours'] = $data['last_24_hours'] ?? null;
        $this->container['last_7_days'] = $data['last_7_days'] ?? null;
        $this->container['last_30_days'] = $data['last_30_days'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets last_24_hours
     *
     * @return \onesignal\client\model\EmailReputationWindow|null
     */
    public function getLast24Hours()
    {
        return $this->container['last_24_hours'];
    }

    /**
     * Sets last_24_hours
     *
     * @param \onesignal\client\model\EmailReputationWindow|null $last_24_hours last_24_hours
     *
     * @return self
     */
    public function setLast24Hours($last_24_hours)
    {
        $this->container['last_24_hours'] = $last_24_hours;

        return $this;
    }

    /**
     * Gets last_7_days
     *
     * @return \onesignal\client\model\EmailReputationWindow|null
     */
    public function getLast7Days()
    {
        return $this->container['last_7_days'];
    }

    /**
     * Sets last_7_days
     *
     * @param \onesignal\client\model\EmailReputationWindow|null $last_7_days last_7_days
     *
     * @return self
     */
    public function setLast7Days($last_7_days)
    {
        $this->container['last_7_days'] = $last_7_days;

        return $this;
    }

    /**
     * Gets last_30_days
     *
     * @return \onesignal\client\model\EmailReputationWindow|null
     */
    public function getLast30Days()
    {
        return $this->container['last_30_days'];
    }

    /**
     * Sets last_30_days
     *
     * @param \onesignal\client\model\EmailReputationWindow|null $last_30_days last_30_days
     *
     * @return self
     */
    public function setLast30Days($last_30_days)
    {
        $this->container['last_30_days'] = $last_30_days;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


