<?php
/**
 * EstimateNotificationRecipientsSuccessResponse
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  onesignal\client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace onesignal\client\model;

use \ArrayAccess;
use \onesignal\client\ObjectSerializer;

/**
 * EstimateNotificationRecipientsSuccessResponse Class Doc Comment
 *
 * @category Class
 * @package  onesignal\client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class EstimateNotificationRecipientsSuccessResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EstimateNotificationRecipientsSuccessResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'count' => 'int',
        'uncapped_count' => 'int',
        'cap_applied' => 'bool',
        'mobile_suppressed' => 'bool',
        'mobile_excluded_count' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'count' => null,
        'uncapped_count' => null,
        'cap_applied' => null,
        'mobile_suppressed' => null,
        'mobile_excluded_count' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'count' => 'count',
        'uncapped_count' => 'uncapped_count',
        'cap_applied' => 'cap_applied',
        'mobile_suppressed' => 'mobile_suppressed',
        'mobile_excluded_count' => 'mobile_excluded_count'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'count' => 'setCount',
        'uncapped_count' => 'setUncappedCount',
        'cap_applied' => 'setCapApplied',
        'mobile_suppressed' => 'setMobileSuppressed',
        'mobile_excluded_count' => 'setMobileExcludedCount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'count' => 'getCount',
        'uncapped_count' => 'getUncappedCount',
        'cap_applied' => 'getCapApplied',
        'mobile_suppressed' => 'getMobileSuppressed',
        'mobile_excluded_count' => 'getMobileExcludedCount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['count'] = $data['count'] ?? null;
        $this->container['uncapped_count'] = $data['uncapped_count'] ?? null;
        $this->container['cap_applied'] = $data['cap_applied'] ?? null;
        $this->container['mobile_suppressed'] = $data['mobile_suppressed'] ?? null;
        $this->container['mobile_excluded_count'] = $data['mobile_excluded_count'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets count
     *
     * @return int|null
     */
    public function getCount()
    {
        return $this->container['count'];
    }

    /**
     * Sets count
     *
     * @param int|null $count The estimated audience size based on the user targeting method you've set on the message, and the specific platforms the message is targeted to send to.
     *
     * @return self
     */
    public function setCount($count)
    {
        $this->container['count'] = $count;

        return $this;
    }

    /**
     * Gets uncapped_count
     *
     * @return int|null
     */
    public function getUncappedCount()
    {
        return $this->container['uncapped_count'];
    }

    /**
     * Sets uncapped_count
     *
     * @param int|null $uncapped_count The estimated audience size before the plan's web push subscriber cap is applied. Present only when `cap_applied` is `true`; `null` otherwise.
     *
     * @return self
     */
    public function setUncappedCount($uncapped_count)
    {
        $this->container['uncapped_count'] = $uncapped_count;

        return $this;
    }

    /**
     * Gets cap_applied
     *
     * @return bool|null
     */
    public function getCapApplied()
    {
        return $this->container['cap_applied'];
    }

    /**
     * Sets cap_applied
     *
     * @param bool|null $cap_applied Whether `count` was reduced because the app is on a plan that caps the number of web push subscribers it can send to.
     *
     * @return self
     */
    public function setCapApplied($cap_applied)
    {
        $this->container['cap_applied'] = $cap_applied;

        return $this;
    }

    /**
     * Gets mobile_suppressed
     *
     * @return bool|null
     */
    public function getMobileSuppressed()
    {
        return $this->container['mobile_suppressed'];
    }

    /**
     * Sets mobile_suppressed
     *
     * @param bool|null $mobile_suppressed The mobile equivalent of `cap_applied`. Whether mobile push deliveries will be dropped for this send because the org is over its plan's mobile push subscriber cap. `false` when the notification doesn't target any mobile push platforms.
     *
     * @return self
     */
    public function setMobileSuppressed($mobile_suppressed)
    {
        $this->container['mobile_suppressed'] = $mobile_suppressed;

        return $this;
    }

    /**
     * Gets mobile_excluded_count
     *
     * @return int|null
     */
    public function getMobileExcludedCount()
    {
        return $this->container['mobile_excluded_count'];
    }

    /**
     * Sets mobile_excluded_count
     *
     * @param int|null $mobile_excluded_count How many mobile push recipients the `count` excludes due to the plan's mobile push subscriber cap. `0` when `mobile_suppressed` is `false`.
     *
     * @return self
     */
    public function setMobileExcludedCount($mobile_excluded_count)
    {
        $this->container['mobile_excluded_count'] = $mobile_excluded_count;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


