<?php
/**
 * JourneyEarlyExitRules
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  onesignal\client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace onesignal\client\model;

use \ArrayAccess;
use \onesignal\client\ObjectSerializer;

/**
 * JourneyEarlyExitRules Class Doc Comment
 *
 * @category Class
 * @package  onesignal\client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class JourneyEarlyExitRules implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'JourneyEarlyExit_rules';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'on_segment' => '\onesignal\client\model\JourneyEarlyExitRulesOnSegment',
        'when_not_in_audience' => 'bool',
        'on_session' => 'bool',
        'on_event' => '\onesignal\client\model\JourneyEarlyExitRulesOnEvent'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'on_segment' => null,
        'when_not_in_audience' => null,
        'on_session' => null,
        'on_event' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'on_segment' => 'on_segment',
        'when_not_in_audience' => 'when_not_in_audience',
        'on_session' => 'on_session',
        'on_event' => 'on_event'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'on_segment' => 'setOnSegment',
        'when_not_in_audience' => 'setWhenNotInAudience',
        'on_session' => 'setOnSession',
        'on_event' => 'setOnEvent'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'on_segment' => 'getOnSegment',
        'when_not_in_audience' => 'getWhenNotInAudience',
        'on_session' => 'getOnSession',
        'on_event' => 'getOnEvent'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['on_segment'] = $data['on_segment'] ?? null;
        $this->container['when_not_in_audience'] = $data['when_not_in_audience'] ?? null;
        $this->container['on_session'] = $data['on_session'] ?? null;
        $this->container['on_event'] = $data['on_event'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets on_segment
     *
     * @return \onesignal\client\model\JourneyEarlyExitRulesOnSegment|null
     */
    public function getOnSegment()
    {
        return $this->container['on_segment'];
    }

    /**
     * Sets on_segment
     *
     * @param \onesignal\client\model\JourneyEarlyExitRulesOnSegment|null $on_segment on_segment
     *
     * @return self
     */
    public function setOnSegment($on_segment)
    {
        $this->container['on_segment'] = $on_segment;

        return $this;
    }

    /**
     * Gets when_not_in_audience
     *
     * @return bool|null
     */
    public function getWhenNotInAudience()
    {
        return $this->container['when_not_in_audience'];
    }

    /**
     * Sets when_not_in_audience
     *
     * @param bool|null $when_not_in_audience Exit when the user no longer matches the journey audience. Defaults to false.
     *
     * @return self
     */
    public function setWhenNotInAudience($when_not_in_audience)
    {
        $this->container['when_not_in_audience'] = $when_not_in_audience;

        return $this;
    }

    /**
     * Gets on_session
     *
     * @return bool|null
     */
    public function getOnSession()
    {
        return $this->container['on_session'];
    }

    /**
     * Sets on_session
     *
     * @param bool|null $on_session Exit on a new session start. Defaults to false.
     *
     * @return self
     */
    public function setOnSession($on_session)
    {
        $this->container['on_session'] = $on_session;

        return $this;
    }

    /**
     * Gets on_event
     *
     * @return \onesignal\client\model\JourneyEarlyExitRulesOnEvent|null
     */
    public function getOnEvent()
    {
        return $this->container['on_event'];
    }

    /**
     * Sets on_event
     *
     * @param \onesignal\client\model\JourneyEarlyExitRulesOnEvent|null $on_event on_event
     *
     * @return self
     */
    public function setOnEvent($on_event)
    {
        $this->container['on_event'] = $on_event;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


