<?php
/**
 * JourneyNodeStats
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  onesignal\client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace onesignal\client\model;

use \ArrayAccess;
use \onesignal\client\ObjectSerializer;

/**
 * JourneyNodeStats Class Doc Comment
 *
 * @category Class
 * @description Stats for a single node. Keyed in the response by the node&#39;s server-assigned id.
 * @package  onesignal\client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class JourneyNodeStats implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'JourneyNodeStats';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'kind' => 'string',
        'waiting' => 'int',
        'completed' => 'int',
        'exited_early' => 'int',
        'message_stats' => '\onesignal\client\model\JourneyMessageStats'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'kind' => null,
        'waiting' => null,
        'completed' => null,
        'exited_early' => null,
        'message_stats' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'kind' => 'kind',
        'waiting' => 'waiting',
        'completed' => 'completed',
        'exited_early' => 'exited_early',
        'message_stats' => 'message_stats'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'kind' => 'setKind',
        'waiting' => 'setWaiting',
        'completed' => 'setCompleted',
        'exited_early' => 'setExitedEarly',
        'message_stats' => 'setMessageStats'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'kind' => 'getKind',
        'waiting' => 'getWaiting',
        'completed' => 'getCompleted',
        'exited_early' => 'getExitedEarly',
        'message_stats' => 'getMessageStats'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const KIND_WAIT = 'wait';
    public const KIND_TIME_WINDOW = 'time_window';
    public const KIND_SEND_PUSH = 'send_push';
    public const KIND_SEND_EMAIL = 'send_email';
    public const KIND_SEND_SMS = 'send_sms';
    public const KIND_SEND_IAM = 'send_iam';
    public const KIND_SEND_WEBHOOK = 'send_webhook';
    public const KIND_TAG = 'tag';
    public const KIND_SPLIT_RANGE = 'split_range';
    public const KIND_YES_NO = 'yes_no';
    public const KIND_WAIT_UNTIL = 'wait_until';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getKindAllowableValues()
    {
        return [
            self::KIND_WAIT,
            self::KIND_TIME_WINDOW,
            self::KIND_SEND_PUSH,
            self::KIND_SEND_EMAIL,
            self::KIND_SEND_SMS,
            self::KIND_SEND_IAM,
            self::KIND_SEND_WEBHOOK,
            self::KIND_TAG,
            self::KIND_SPLIT_RANGE,
            self::KIND_YES_NO,
            self::KIND_WAIT_UNTIL,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['kind'] = $data['kind'] ?? null;
        $this->container['waiting'] = $data['waiting'] ?? null;
        $this->container['completed'] = $data['completed'] ?? null;
        $this->container['exited_early'] = $data['exited_early'] ?? null;
        $this->container['message_stats'] = $data['message_stats'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getKindAllowableValues();
        if (!is_null($this->container['kind']) && !in_array($this->container['kind'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'kind', must be one of '%s'",
                $this->container['kind'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets kind
     *
     * @return string|null
     */
    public function getKind()
    {
        return $this->container['kind'];
    }

    /**
     * Sets kind
     *
     * @param string|null $kind Node kind, repeated here so stats can be read without joining against the journey definition.
     *
     * @return self
     */
    public function setKind($kind)
    {
        $allowedValues = $this->getKindAllowableValues();
        if (!is_null($kind) && !in_array($kind, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'kind', must be one of '%s'",
                    $kind,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['kind'] = $kind;

        return $this;
    }

    /**
     * Gets waiting
     *
     * @return int|null
     */
    public function getWaiting()
    {
        return $this->container['waiting'];
    }

    /**
     * Sets waiting
     *
     * @param int|null $waiting Users currently held at this node.
     *
     * @return self
     */
    public function setWaiting($waiting)
    {
        $this->container['waiting'] = $waiting;

        return $this;
    }

    /**
     * Gets completed
     *
     * @return int|null
     */
    public function getCompleted()
    {
        return $this->container['completed'];
    }

    /**
     * Sets completed
     *
     * @param int|null $completed Users who advanced past this node normally.
     *
     * @return self
     */
    public function setCompleted($completed)
    {
        $this->container['completed'] = $completed;

        return $this;
    }

    /**
     * Gets exited_early
     *
     * @return int|null
     */
    public function getExitedEarly()
    {
        return $this->container['exited_early'];
    }

    /**
     * Sets exited_early
     *
     * @param int|null $exited_early Users who left the journey from this node through an early exit rule.
     *
     * @return self
     */
    public function setExitedEarly($exited_early)
    {
        $this->container['exited_early'] = $exited_early;

        return $this;
    }

    /**
     * Gets message_stats
     *
     * @return \onesignal\client\model\JourneyMessageStats|null
     */
    public function getMessageStats()
    {
        return $this->container['message_stats'];
    }

    /**
     * Sets message_stats
     *
     * @param \onesignal\client\model\JourneyMessageStats|null $message_stats message_stats
     *
     * @return self
     */
    public function setMessageStats($message_stats)
    {
        $this->container['message_stats'] = $message_stats;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


