<?php
/**
 * JourneyCondition
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  onesignal\client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace onesignal\client\model;

use \ArrayAccess;
use \onesignal\client\ObjectSerializer;

/**
 * JourneyCondition Class Doc Comment
 *
 * @category Class
 * @description A branch condition. The kind field selects which other fields apply.
 * @package  onesignal\client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class JourneyCondition implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'JourneyCondition';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'kind' => 'string',
        'included_segment_ids' => 'string[]',
        'excluded_segment_ids' => 'string[]',
        'action' => 'string',
        'sending_node_id' => 'string',
        'client_node_id' => 'string',
        'name' => 'string',
        'attributes' => '\onesignal\client\model\JourneyEventAttribute[][]',
        'entry_event_match_attributes' => 'object[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'kind' => null,
        'included_segment_ids' => null,
        'excluded_segment_ids' => null,
        'action' => null,
        'sending_node_id' => null,
        'client_node_id' => null,
        'name' => null,
        'attributes' => null,
        'entry_event_match_attributes' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'kind' => 'kind',
        'included_segment_ids' => 'included_segment_ids',
        'excluded_segment_ids' => 'excluded_segment_ids',
        'action' => 'action',
        'sending_node_id' => 'sending_node_id',
        'client_node_id' => 'client_node_id',
        'name' => 'name',
        'attributes' => 'attributes',
        'entry_event_match_attributes' => 'entry_event_match_attributes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'kind' => 'setKind',
        'included_segment_ids' => 'setIncludedSegmentIds',
        'excluded_segment_ids' => 'setExcludedSegmentIds',
        'action' => 'setAction',
        'sending_node_id' => 'setSendingNodeId',
        'client_node_id' => 'setClientNodeId',
        'name' => 'setName',
        'attributes' => 'setAttributes',
        'entry_event_match_attributes' => 'setEntryEventMatchAttributes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'kind' => 'getKind',
        'included_segment_ids' => 'getIncludedSegmentIds',
        'excluded_segment_ids' => 'getExcludedSegmentIds',
        'action' => 'getAction',
        'sending_node_id' => 'getSendingNodeId',
        'client_node_id' => 'getClientNodeId',
        'name' => 'getName',
        'attributes' => 'getAttributes',
        'entry_event_match_attributes' => 'getEntryEventMatchAttributes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const KIND_SEGMENT_MEMBERSHIP = 'segment_membership';
    public const KIND_ON_NOTIFICATION_ACTION = 'on_notification_action';
    public const KIND_EVENT_TRIGGER = 'event_trigger';
    public const ACTION_RECEIVED = 'received';
    public const ACTION_CLICKED = 'clicked';
    public const ACTION_OPENED = 'opened';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getKindAllowableValues()
    {
        return [
            self::KIND_SEGMENT_MEMBERSHIP,
            self::KIND_ON_NOTIFICATION_ACTION,
            self::KIND_EVENT_TRIGGER,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getActionAllowableValues()
    {
        return [
            self::ACTION_RECEIVED,
            self::ACTION_CLICKED,
            self::ACTION_OPENED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['kind'] = $data['kind'] ?? null;
        $this->container['included_segment_ids'] = $data['included_segment_ids'] ?? null;
        $this->container['excluded_segment_ids'] = $data['excluded_segment_ids'] ?? null;
        $this->container['action'] = $data['action'] ?? null;
        $this->container['sending_node_id'] = $data['sending_node_id'] ?? null;
        $this->container['client_node_id'] = $data['client_node_id'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['attributes'] = $data['attributes'] ?? null;
        $this->container['entry_event_match_attributes'] = $data['entry_event_match_attributes'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['kind'] === null) {
            $invalidProperties[] = "'kind' can't be null";
        }
        $allowedValues = $this->getKindAllowableValues();
        if (!is_null($this->container['kind']) && !in_array($this->container['kind'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'kind', must be one of '%s'",
                $this->container['kind'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getActionAllowableValues();
        if (!is_null($this->container['action']) && !in_array($this->container['action'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'action', must be one of '%s'",
                $this->container['action'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets kind
     *
     * @return string
     */
    public function getKind()
    {
        return $this->container['kind'];
    }

    /**
     * Sets kind
     *
     * @param string $kind Condition kind. Selects which other fields apply.
     *
     * @return self
     */
    public function setKind($kind)
    {
        $allowedValues = $this->getKindAllowableValues();
        if (!in_array($kind, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'kind', must be one of '%s'",
                    $kind,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['kind'] = $kind;

        return $this;
    }

    /**
     * Gets included_segment_ids
     *
     * @return string[]|null
     */
    public function getIncludedSegmentIds()
    {
        return $this->container['included_segment_ids'];
    }

    /**
     * Sets included_segment_ids
     *
     * @param string[]|null $included_segment_ids segment_membership conditions: Segment UUIDs the user must belong to.
     *
     * @return self
     */
    public function setIncludedSegmentIds($included_segment_ids)
    {
        $this->container['included_segment_ids'] = $included_segment_ids;

        return $this;
    }

    /**
     * Gets excluded_segment_ids
     *
     * @return string[]|null
     */
    public function getExcludedSegmentIds()
    {
        return $this->container['excluded_segment_ids'];
    }

    /**
     * Sets excluded_segment_ids
     *
     * @param string[]|null $excluded_segment_ids segment_membership conditions: Segment UUIDs the user must not belong to.
     *
     * @return self
     */
    public function setExcludedSegmentIds($excluded_segment_ids)
    {
        $this->container['excluded_segment_ids'] = $excluded_segment_ids;

        return $this;
    }

    /**
     * Gets action
     *
     * @return string|null
     */
    public function getAction()
    {
        return $this->container['action'];
    }

    /**
     * Sets action
     *
     * @param string|null $action on_notification_action conditions: the notification action to branch on. Which actions apply depends on the sending node's channel.
     *
     * @return self
     */
    public function setAction($action)
    {
        $allowedValues = $this->getActionAllowableValues();
        if (!is_null($action) && !in_array($action, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'action', must be one of '%s'",
                    $action,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['action'] = $action;

        return $this;
    }

    /**
     * Gets sending_node_id
     *
     * @return string|null
     */
    public function getSendingNodeId()
    {
        return $this->container['sending_node_id'];
    }

    /**
     * Sets sending_node_id
     *
     * @param string|null $sending_node_id on_notification_action conditions: id of the sending node this action refers to. Returned on reads; accepted on write.
     *
     * @return self
     */
    public function setSendingNodeId($sending_node_id)
    {
        $this->container['sending_node_id'] = $sending_node_id;

        return $this;
    }

    /**
     * Gets client_node_id
     *
     * @return string|null
     */
    public function getClientNodeId()
    {
        return $this->container['client_node_id'];
    }

    /**
     * Sets client_node_id
     *
     * @param string|null $client_node_id on_notification_action conditions: write-only alternative to sending_node_id. References the sending node by its client_node_id.
     *
     * @return self
     */
    public function setClientNodeId($client_node_id)
    {
        $this->container['client_node_id'] = $client_node_id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name event_trigger conditions: event name, up to 255 characters.
     *
     * @return self
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets attributes
     *
     * @return \onesignal\client\model\JourneyEventAttribute[][]|null
     */
    public function getAttributes()
    {
        return $this->container['attributes'];
    }

    /**
     * Sets attributes
     *
     * @param \onesignal\client\model\JourneyEventAttribute[][]|null $attributes Event attribute matchers, as a list of condition groups. Send a single group whose conditions are AND'd together. More than one group is rejected.
     *
     * @return self
     */
    public function setAttributes($attributes)
    {
        $this->container['attributes'] = $attributes;

        return $this;
    }

    /**
     * Gets entry_event_match_attributes
     *
     * @return object[]|null
     */
    public function getEntryEventMatchAttributes()
    {
        return $this->container['entry_event_match_attributes'];
    }

    /**
     * Sets entry_event_match_attributes
     *
     * @param object[]|null $entry_event_match_attributes event_trigger conditions: match incoming event properties against the journey's entry event. Only valid on event-triggered journeys.
     *
     * @return self
     */
    public function setEntryEventMatchAttributes($entry_event_match_attributes)
    {
        $this->container['entry_event_match_attributes'] = $entry_event_match_attributes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


