<?php
/**
 * UpdateJourneyNodeRequest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  onesignal\client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace onesignal\client\model;

use \ArrayAccess;
use \onesignal\client\ObjectSerializer;

/**
 * UpdateJourneyNodeRequest Class Doc Comment
 *
 * @category Class
 * @description Node fields to change, merged onto the current node. Send only the fields you want to change. The node&#39;s kind and id cannot be changed. Send null to clear a nullable field. Which other fields apply depends on the node&#39;s kind, matching JourneyNode.
 * @package  onesignal\client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class UpdateJourneyNodeRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'UpdateJourneyNodeRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'client_node_id' => 'string',
        'annotation' => 'string',
        'duration_seconds' => 'int',
        'relative_to' => 'string',
        'windows' => '\onesignal\client\model\JourneyTimeWindow[]',
        'time_zone' => 'string',
        'use_user_time_zone' => 'bool',
        'template_id' => 'string',
        'iam_id' => 'string',
        'user_ttl_seconds' => 'int',
        'webhook_id' => 'string',
        'assignments' => 'array<string,string>',
        'randomize_on_entry' => 'bool',
        'branches' => '\onesignal\client\model\JourneyBranch[]',
        'expiration' => '\onesignal\client\model\JourneyWaitUntilExpiration',
        'concurrency_key' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'client_node_id' => null,
        'annotation' => null,
        'duration_seconds' => null,
        'relative_to' => null,
        'windows' => null,
        'time_zone' => null,
        'use_user_time_zone' => null,
        'template_id' => null,
        'iam_id' => null,
        'user_ttl_seconds' => null,
        'webhook_id' => null,
        'assignments' => null,
        'randomize_on_entry' => null,
        'branches' => null,
        'expiration' => null,
        'concurrency_key' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'client_node_id' => 'client_node_id',
        'annotation' => 'annotation',
        'duration_seconds' => 'duration_seconds',
        'relative_to' => 'relative_to',
        'windows' => 'windows',
        'time_zone' => 'time_zone',
        'use_user_time_zone' => 'use_user_time_zone',
        'template_id' => 'template_id',
        'iam_id' => 'iam_id',
        'user_ttl_seconds' => 'user_ttl_seconds',
        'webhook_id' => 'webhook_id',
        'assignments' => 'assignments',
        'randomize_on_entry' => 'randomize_on_entry',
        'branches' => 'branches',
        'expiration' => 'expiration',
        'concurrency_key' => 'concurrency_key'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'client_node_id' => 'setClientNodeId',
        'annotation' => 'setAnnotation',
        'duration_seconds' => 'setDurationSeconds',
        'relative_to' => 'setRelativeTo',
        'windows' => 'setWindows',
        'time_zone' => 'setTimeZone',
        'use_user_time_zone' => 'setUseUserTimeZone',
        'template_id' => 'setTemplateId',
        'iam_id' => 'setIamId',
        'user_ttl_seconds' => 'setUserTtlSeconds',
        'webhook_id' => 'setWebhookId',
        'assignments' => 'setAssignments',
        'randomize_on_entry' => 'setRandomizeOnEntry',
        'branches' => 'setBranches',
        'expiration' => 'setExpiration',
        'concurrency_key' => 'setConcurrencyKey'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'client_node_id' => 'getClientNodeId',
        'annotation' => 'getAnnotation',
        'duration_seconds' => 'getDurationSeconds',
        'relative_to' => 'getRelativeTo',
        'windows' => 'getWindows',
        'time_zone' => 'getTimeZone',
        'use_user_time_zone' => 'getUseUserTimeZone',
        'template_id' => 'getTemplateId',
        'iam_id' => 'getIamId',
        'user_ttl_seconds' => 'getUserTtlSeconds',
        'webhook_id' => 'getWebhookId',
        'assignments' => 'getAssignments',
        'randomize_on_entry' => 'getRandomizeOnEntry',
        'branches' => 'getBranches',
        'expiration' => 'getExpiration',
        'concurrency_key' => 'getConcurrencyKey'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const RELATIVE_TO_SCHEDULE_IN_TIMEZONE = 'schedule_in_timezone';
    public const RELATIVE_TO_LAST_ACTIVE_TIME = 'last_active_time';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRelativeToAllowableValues()
    {
        return [
            self::RELATIVE_TO_SCHEDULE_IN_TIMEZONE,
            self::RELATIVE_TO_LAST_ACTIVE_TIME,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['client_node_id'] = $data['client_node_id'] ?? null;
        $this->container['annotation'] = $data['annotation'] ?? null;
        $this->container['duration_seconds'] = $data['duration_seconds'] ?? null;
        $this->container['relative_to'] = $data['relative_to'] ?? null;
        $this->container['windows'] = $data['windows'] ?? null;
        $this->container['time_zone'] = $data['time_zone'] ?? null;
        $this->container['use_user_time_zone'] = $data['use_user_time_zone'] ?? null;
        $this->container['template_id'] = $data['template_id'] ?? null;
        $this->container['iam_id'] = $data['iam_id'] ?? null;
        $this->container['user_ttl_seconds'] = $data['user_ttl_seconds'] ?? null;
        $this->container['webhook_id'] = $data['webhook_id'] ?? null;
        $this->container['assignments'] = $data['assignments'] ?? null;
        $this->container['randomize_on_entry'] = $data['randomize_on_entry'] ?? null;
        $this->container['branches'] = $data['branches'] ?? null;
        $this->container['expiration'] = $data['expiration'] ?? null;
        $this->container['concurrency_key'] = $data['concurrency_key'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['duration_seconds']) && ($this->container['duration_seconds'] > 31556952)) {
            $invalidProperties[] = "invalid value for 'duration_seconds', must be smaller than or equal to 31556952.";
        }

        if (!is_null($this->container['duration_seconds']) && ($this->container['duration_seconds'] < 60)) {
            $invalidProperties[] = "invalid value for 'duration_seconds', must be bigger than or equal to 60.";
        }

        $allowedValues = $this->getRelativeToAllowableValues();
        if (!is_null($this->container['relative_to']) && !in_array($this->container['relative_to'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'relative_to', must be one of '%s'",
                $this->container['relative_to'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['user_ttl_seconds']) && ($this->container['user_ttl_seconds'] < 1)) {
            $invalidProperties[] = "invalid value for 'user_ttl_seconds', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets client_node_id
     *
     * @return string|null
     */
    public function getClientNodeId()
    {
        return $this->container['client_node_id'];
    }

    /**
     * Sets client_node_id
     *
     * @param string|null $client_node_id Optional client-assigned identifier, unique within the journey. Use it to reference this node from elsewhere in the same request. Persisted and returned on reads.
     *
     * @return self
     */
    public function setClientNodeId($client_node_id)
    {
        $this->container['client_node_id'] = $client_node_id;

        return $this;
    }

    /**
     * Gets annotation
     *
     * @return string|null
     */
    public function getAnnotation()
    {
        return $this->container['annotation'];
    }

    /**
     * Sets annotation
     *
     * @param string|null $annotation Optional free-text label, up to 255 characters. Stored and returned as-is with no effect on journey behavior.
     *
     * @return self
     */
    public function setAnnotation($annotation)
    {
        $this->container['annotation'] = $annotation;

        return $this;
    }

    /**
     * Gets duration_seconds
     *
     * @return int|null
     */
    public function getDurationSeconds()
    {
        return $this->container['duration_seconds'];
    }

    /**
     * Sets duration_seconds
     *
     * @param int|null $duration_seconds wait nodes: seconds to hold the user. Minimum 60, maximum 31556952 (1 year).
     *
     * @return self
     */
    public function setDurationSeconds($duration_seconds)
    {

        if (!is_null($duration_seconds) && ($duration_seconds > 31556952)) {
            throw new \InvalidArgumentException('invalid value for $duration_seconds when calling UpdateJourneyNodeRequest., must be smaller than or equal to 31556952.');
        }
        if (!is_null($duration_seconds) && ($duration_seconds < 60)) {
            throw new \InvalidArgumentException('invalid value for $duration_seconds when calling UpdateJourneyNodeRequest., must be bigger than or equal to 60.');
        }

        $this->container['duration_seconds'] = $duration_seconds;

        return $this;
    }

    /**
     * Gets relative_to
     *
     * @return string|null
     */
    public function getRelativeTo()
    {
        return $this->container['relative_to'];
    }

    /**
     * Sets relative_to
     *
     * @param string|null $relative_to time_window nodes: schedule_in_timezone uses the configured windows; last_active_time holds relative to the user's last active time.
     *
     * @return self
     */
    public function setRelativeTo($relative_to)
    {
        $allowedValues = $this->getRelativeToAllowableValues();
        if (!is_null($relative_to) && !in_array($relative_to, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'relative_to', must be one of '%s'",
                    $relative_to,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['relative_to'] = $relative_to;

        return $this;
    }

    /**
     * Gets windows
     *
     * @return \onesignal\client\model\JourneyTimeWindow[]|null
     */
    public function getWindows()
    {
        return $this->container['windows'];
    }

    /**
     * Sets windows
     *
     * @param \onesignal\client\model\JourneyTimeWindow[]|null $windows time_window nodes: one or more time windows. A window with no day_of_week applies to every day. Required when relative_to is schedule_in_timezone; omit when it is last_active_time.
     *
     * @return self
     */
    public function setWindows($windows)
    {
        $this->container['windows'] = $windows;

        return $this;
    }

    /**
     * Gets time_zone
     *
     * @return string|null
     */
    public function getTimeZone()
    {
        return $this->container['time_zone'];
    }

    /**
     * Sets time_zone
     *
     * @param string|null $time_zone time_window nodes: IANA timezone identifier used when the user's timezone is unavailable.
     *
     * @return self
     */
    public function setTimeZone($time_zone)
    {
        $this->container['time_zone'] = $time_zone;

        return $this;
    }

    /**
     * Gets use_user_time_zone
     *
     * @return bool|null
     */
    public function getUseUserTimeZone()
    {
        return $this->container['use_user_time_zone'];
    }

    /**
     * Sets use_user_time_zone
     *
     * @param bool|null $use_user_time_zone time_window nodes: when true, uses the user's timezone if available.
     *
     * @return self
     */
    public function setUseUserTimeZone($use_user_time_zone)
    {
        $this->container['use_user_time_zone'] = $use_user_time_zone;

        return $this;
    }

    /**
     * Gets template_id
     *
     * @return string|null
     */
    public function getTemplateId()
    {
        return $this->container['template_id'];
    }

    /**
     * Sets template_id
     *
     * @param string|null $template_id send_push, send_email, and send_sms nodes: UUID of the template to send.
     *
     * @return self
     */
    public function setTemplateId($template_id)
    {
        $this->container['template_id'] = $template_id;

        return $this;
    }

    /**
     * Gets iam_id
     *
     * @return string|null
     */
    public function getIamId()
    {
        return $this->container['iam_id'];
    }

    /**
     * Sets iam_id
     *
     * @param string|null $iam_id send_iam nodes: UUID of the in-app message to send.
     *
     * @return self
     */
    public function setIamId($iam_id)
    {
        $this->container['iam_id'] = $iam_id;

        return $this;
    }

    /**
     * Gets user_ttl_seconds
     *
     * @return int|null
     */
    public function getUserTtlSeconds()
    {
        return $this->container['user_ttl_seconds'];
    }

    /**
     * Sets user_ttl_seconds
     *
     * @param int|null $user_ttl_seconds send_iam nodes: optional time-to-live for the in-app message, in seconds.
     *
     * @return self
     */
    public function setUserTtlSeconds($user_ttl_seconds)
    {

        if (!is_null($user_ttl_seconds) && ($user_ttl_seconds < 1)) {
            throw new \InvalidArgumentException('invalid value for $user_ttl_seconds when calling UpdateJourneyNodeRequest., must be bigger than or equal to 1.');
        }

        $this->container['user_ttl_seconds'] = $user_ttl_seconds;

        return $this;
    }

    /**
     * Gets webhook_id
     *
     * @return string|null
     */
    public function getWebhookId()
    {
        return $this->container['webhook_id'];
    }

    /**
     * Sets webhook_id
     *
     * @param string|null $webhook_id send_webhook nodes: UUID of the webhook to send.
     *
     * @return self
     */
    public function setWebhookId($webhook_id)
    {
        $this->container['webhook_id'] = $webhook_id;

        return $this;
    }

    /**
     * Gets assignments
     *
     * @return array<string,string>|null
     */
    public function getAssignments()
    {
        return $this->container['assignments'];
    }

    /**
     * Sets assignments
     *
     * @param array<string,string>|null $assignments tag nodes: tag key-value pairs to assign. An empty string value removes the tag. Keys are limited to 255 characters and values to 1024.
     *
     * @return self
     */
    public function setAssignments($assignments)
    {
        $this->container['assignments'] = $assignments;

        return $this;
    }

    /**
     * Gets randomize_on_entry
     *
     * @return bool|null
     */
    public function getRandomizeOnEntry()
    {
        return $this->container['randomize_on_entry'];
    }

    /**
     * Sets randomize_on_entry
     *
     * @param bool|null $randomize_on_entry split_range nodes: when true, assigns each user to a branch at random on entry. Defaults to false.
     *
     * @return self
     */
    public function setRandomizeOnEntry($randomize_on_entry)
    {
        $this->container['randomize_on_entry'] = $randomize_on_entry;

        return $this;
    }

    /**
     * Gets branches
     *
     * @return \onesignal\client\model\JourneyBranch[]|null
     */
    public function getBranches()
    {
        return $this->container['branches'];
    }

    /**
     * Sets branches
     *
     * @param \onesignal\client\model\JourneyBranch[]|null $branches Branching nodes: nested branches. split_range requires 2-20 weighted branches that sum to 100. yes_no requires exactly 2 branches. wait_until requires 1-10 condition branches.
     *
     * @return self
     */
    public function setBranches($branches)
    {
        $this->container['branches'] = $branches;

        return $this;
    }

    /**
     * Gets expiration
     *
     * @return \onesignal\client\model\JourneyWaitUntilExpiration|null
     */
    public function getExpiration()
    {
        return $this->container['expiration'];
    }

    /**
     * Sets expiration
     *
     * @param \onesignal\client\model\JourneyWaitUntilExpiration|null $expiration expiration
     *
     * @return self
     */
    public function setExpiration($expiration)
    {
        $this->container['expiration'] = $expiration;

        return $this;
    }

    /**
     * Gets concurrency_key
     *
     * @return string|null
     */
    public function getConcurrencyKey()
    {
        return $this->container['concurrency_key'];
    }

    /**
     * Sets concurrency_key
     *
     * @param string|null $concurrency_key Optional optimistic-concurrency token. Pass the concurrency_key from a prior fetch to reject the update with 409 if the journey changed. Omit to skip the check. It is not merged onto the node.
     *
     * @return self
     */
    public function setConcurrencyKey($concurrency_key)
    {
        $this->container['concurrency_key'] = $concurrency_key;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


