<?php
/**
 * ApiException
 * PHP version 7.3
 *
 * @category Class
 * @package  onesignal\client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.11.1
 * Contact: devrel@onesignal.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace onesignal\client;

use \Exception;

/**
 * ApiException Class Doc Comment
 *
 * @category Class
 * @package  onesignal\client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ApiException extends Exception
{
    /**
     * The HTTP body of the server response either as Json or string.
     *
     * @var \stdClass|string|null
     */
    protected $responseBody;

    /**
     * The HTTP header of the server response.
     *
     * @var string[]|null
     */
    protected $responseHeaders;

    /**
     * The deserialized response object
     *
     * @var \stdClass|string|null
     */
    protected $responseObject;

    /**
     * Constructor
     *
     * @param string                $message         Error message
     * @param int                   $code            HTTP status code
     * @param string[]|null         $responseHeaders HTTP response header
     * @param \stdClass|string|null $responseBody    HTTP decoded body of the server response either as \stdClass or string
     */
    public function __construct($message = "", $code = 0, $responseHeaders = [], $responseBody = null)
    {
        parent::__construct($message, $code);
        $this->responseHeaders = $responseHeaders;
        $this->responseBody = $responseBody;
    }

    /**
     * Gets the HTTP response header
     *
     * @return string[]|null HTTP response header
     */
    public function getResponseHeaders()
    {
        return $this->responseHeaders;
    }

    /**
     * Gets the HTTP body of the server response either as Json or string
     *
     * @return \stdClass|string|null HTTP body of the server response either as \stdClass or string
     */
    public function getResponseBody()
    {
        return $this->responseBody;
    }

    /**
     * Sets the deserialized response object (during deserialization)
     *
     * @param mixed $obj Deserialized response object
     *
     * @return void
     */
    public function setResponseObject($obj)
    {
        $this->responseObject = $obj;
    }

    /**
     * Gets the deserialized response object (during deserialization)
     *
     * @return mixed the deserialized response object
     */
    public function getResponseObject()
    {
        return $this->responseObject;
    }

    /**
     * Gets the error messages carried by the response body, normalized to a
     * flat string array regardless of which envelope shape the API returned
     * (`{ "errors": "..." }`, `{ "errors": ["..."] }`,
     * `{ "errors": [{ "code": ..., "title": ... }] }`, or an object map such as
     * `{ "errors": { "invalid_aliases": {...} } }`, surfaced as `"<key>: <value>"`
     * entries). Returns an empty array when the body is not a recognizable error
     * envelope. The raw body remains available via getResponseBody().
     *
     * @return string[]
     */
    public function getErrorMessages()
    {
        $body = $this->responseBody;
        if (is_string($body)) {
            $body = json_decode($body);
            if ($body === null) {
                return [];
            }
        }

        $errors = null;
        if (is_object($body) && isset($body->errors)) {
            $errors = $body->errors;
        } elseif (is_array($body) && isset($body['errors'])) {
            $errors = $body['errors'];
        }

        if (is_string($errors)) {
            return [$errors];
        }
        if (is_array($errors)) {
            $messages = [];
            foreach ($errors as $error) {
                if (is_string($error)) {
                    $messages[] = $error;
                } elseif (is_object($error)) {
                    if (isset($error->title) && $error->title !== '') {
                        $messages[] = $error->title;
                    } elseif (isset($error->code)) {
                        $messages[] = $error->code;
                    }
                } elseif (is_array($error)) {
                    if (isset($error['title']) && $error['title'] !== '') {
                        $messages[] = $error['title'];
                    } elseif (isset($error['code'])) {
                        $messages[] = $error['code'];
                    }
                }
            }
            return $messages;
        }
        if (is_object($errors)) {
            // Object-shaped envelopes (e.g. { "invalid_aliases": {...} }) carry
            // data under arbitrary keys; surface each so it isn't silently
            // dropped. Key order is unspecified, so sort for deterministic output.
            $messages = [];
            foreach (get_object_vars($errors) as $key => $value) {
                $rendered = is_string($value) ? $value : json_encode($value);
                $messages[] = $key . ': ' . $rendered;
            }
            sort($messages);
            return $messages;
        }
        return [];
    }
}
